# Generated by Django 4.0.4 on 2022-05-25 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('TOTE', 'Tote'), ('DRUM', 'Drum'), ('PALE', 'Pale'), ('CANISTER', 'Canister'), (
                    'CAN', 'Can'), ('BAG', 'Bag')], help_text='Select package type', max_length=8, verbose_name='Package type')),
                ('uom', models.CharField(choices=[
                 ('KG', 'kg'), ('LTR', 'ltr')], help_text='Select unit of measure', max_length=3, verbose_name='Unit of measure')),
                ('size', models.PositiveIntegerField(
                    help_text='Enter package size', verbose_name='Package size')),
            ],
            options={
                'verbose_name': 'package',
                'verbose_name_plural': 'packages',
                'ordering': ['size'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter supplier name',
                                          max_length=100, verbose_name='Name')),
                ('country', models.CharField(
                    help_text='Enter supplier country', max_length=60, verbose_name='Country')),
                ('city', models.CharField(help_text='Enter supplier city',
                                          max_length=60, verbose_name='City')),
            ],
            options={
                'verbose_name': 'supplier',
                'verbose_name_plural': 'suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('yzr', models.CharField(blank=True, help_text='Enter yzr code',
                                         max_length=50, null=True, unique=True, verbose_name='YZR code')),
                ('code', models.CharField(help_text='Enter product code',
                                          max_length=50, verbose_name='Product code')),
                ('name', models.CharField(help_text='Enter product name',
                                          max_length=100, verbose_name='Product name')),
                ('formula', models.CharField(choices=[('SB', 'Solventborne'), ('WB', 'Waterborne'), ('PD', 'Powder coating'), (
                    'AC', 'Acid'), ('AM', 'Amine')], help_text='Select formula technology', max_length=2, verbose_name='Formula technology')),
                ('product_type', models.CharField(choices=[('PT', 'Pretreatment'), ('ED', 'Electrocoat'), ('PR', 'Primer'), ('CB', 'Color base'), ('BC', 'Base coat'), ('B1', 'Base 1'), ('B2', 'Base 2'), (
                    'CC', 'Clear coat'), ('MC', 'Monocoat'), ('TH', 'Thinner'), ('CS', 'Cleaning solvent'), ('AD', 'Additive')], help_text='Select product type', max_length=2, verbose_name='Product type')),
                ('package', models.ForeignKey(blank=True, help_text='Select package type', null=True,
                                              on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.package', verbose_name='Package')),
                ('supplier', models.ForeignKey(help_text='Select supplier', on_delete=django.db.models.deletion.CASCADE,
                                               related_name='products', to='products.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['name'],
            },
        ),
    ]
