# Generated by Django 3.2 on 2022-06-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220602_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, help_text='Enter product id code', max_length=50, null=True, unique=True, verbose_name='Product id'),
        ),
    ]
