# Generated by Django 3.2 on 2022-06-02 12:50

import django.core.validators
from django.db import migrations, models
import quality.models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_auto_20220602_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colordata',
            options={'ordering': ['-timestamp', 'batch', 'category'], 'verbose_name': 'color data', 'verbose_name_plural': 'color data'},
        ),
        migrations.AddField(
            model_name='colordata',
            name='color_sheet',
            field=models.FileField(blank=True, help_text='Select file to upload (pdf, jpg, jpeg, png, xls, xlsx, doc, docx)', null=True, upload_to=quality.models.color_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'xls', 'xlsx', 'doc', 'docx'], 'Invalid file extension'), quality.models.file_type_validator], verbose_name='Color sheet'),
        ),
    ]
